site_name: online-shop-multitenant
site_description: Multitenant online shop
repo_url: https://github.com/akshays94/online-shop-multitenant
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/akshays94">akshays94</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
