# Generated by Django 3.0.7 on 2021-05-02 10:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=512)),
                ('last_name', models.CharField(blank=True, max_length=512, null=True)),
                ('email', models.EmailField(max_length=512)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Tenant')),
            ],
            options={
                'unique_together': {('tenant_id', 'email')},
            },
        ),
    ]
