# Generated by Django 3.0.7 on 2021-05-02 10:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='code',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(max_length=256)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
